language: java
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-archetype -Ppublic
branches:
  only:
    - master
    - develop
deploy:
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    on:
      branch: develop
env:
  global:
  - secure: HavGWdAeknN6Q/oL3YyG69aZmH9qGptxYKfvLtMH2aLNiqo3IDDhof6TOgagPk/+sak9DazJTG6eKuBF41oyJEDoxcH7u1rhOtLQDKQvKHOfU6qgdKOGUM7Sc2WnR4U1X75KMp9SuBzPy8qHn9PYkMdjdaxMvDgyrKLelNZbBext3IjDixdK+gxdZi5RJ6UmDGXj5/LmSLAnk+EiBIWb7mqStYHfnyGE4w4Wi52KbyePRTv6UuIvGZ6o48sLW+z1u8yKVYc4eNFiC9OpFnE4ey20CO0H1nsthjM3ubhw4HezyP+DQtWxNi3CbNi231O1lbfaGQMZIeUYImgclY1h5UeaqFnawF+mmPUuRl4O5sd0gcFIfQD86mkWCTqbEHkaJ7sPPYVeEvs9CjX3/hmMiQddddf9HR7sHfd6h2zpsxca58XGoVbsOLZ7ZrXP4ln1GSIFik/H0dV/ialMGa+SILYP6sNJmkjmcf32uBjDODAHg0Kavae1gmzSRSIBVGk35U7IPGSmT8eG0Z67wHhVwFbCthPvi+kODUo9kqlzUhm0bqZGHWj3Oa9SMnABsV06Wv2LDG9FsZRz1nAY100K26UMewTKExHBfwnc/w/CZUyQ7dVl7in+GLolYPYc0cI3QzTGMPk/LxV+kDMB3NOd98oEwur6j0QvOLAd9kaYIc4=
  - secure: WLXGams25BkoOtVqffG01/hlKLW0q6o0zehFPt/TycU26YX6ctJsuELEf9ZZTGfNteEG/1FDesEhMYuRIZdQ0Y4TdVYCCOdphlcJXp1PC07aeVyUL1HroyfV1pMS7NMm0uqx71P6w83Txs5ETbdsdBxhw1SVt8Zt3zEIDKuHEWEJxZWvgL1VWBIOGUBcX91Faa/wHa2qY/6Nnv/pMfExOzs5JWpo+G5e9S/jDlMXez4uLvthlk9o/0pdM7oemPyKAS3IFGGb7p25MMyGXvuqK9eDmcV7ZP19qyJGxdPujaTL2Wpsg9wZ3cJHyEu/AIs9nOxZ4iuk5SSeiCkbWq8njjKwxmrHfbfvQfT49X9StBYjQsK/rk82+SB2/+Y1JM8z7ilP67kTVwIekeyjFxFy27WcZQa2mGPmJJ2y3q2RO7KeUMKHnUlTVf8rohuElq5Qqcdju+C+l3jaGvjl0xiafKN5v8JGlAaU1mdG4648oh8Z8Culz0IC0aJ3nh3fXtY8oAtol98OgS+2ziOLK8VYDPbdLOks2vL+S1NsE3Vb6v8Pf80JamHG7cXARWlFkll8BMVcmqXc6JCXuDaPaR54NUssm+FYzFI0FMA+jF5yvyXpNVCrPr2On1ersmhaeAovYxjSAFlH/7yBL9PHCtFu8/XEh0c6Kj/W+bCLid4pzjQ=
  - secure: TvmmwLtyGsuLcZ3FbZx4H11xExcxXg0OMV+bAMoWhMeX6rFWBFSKf+uggOQ2X3uxRyCHBlB+bxjZqr6sok9CgKHPQAy3lKAZLwpXrIpY91budSd0QHGa7E6HfVdyCykzqEkL8pvMnzK/ETCMBE31/qvNZUGvKKfkxRfKSJyCIGpb1FDvIS0+4Mf8OzUbj3/ue6Ov/wY1wPOKWYQtVM8KJDJJuW2uPbN+ttDDdRc7D5qUJfatkgjHDt+55Wk9tqbuaUhPep/FhF4X7EdrVS8EOborU3P1nSik1bUOAo6906FfBiLym/W90Ha/udos6zKIu908IoJNSK2FfVVvawKdF1qoFnDG5EOvDZCiUlHDj8VvZur5OeusEhoeLQbe6FqGnL/MZev5CMEq/lwE+cHEE5TVmNME4du9/509y4FIrrPj57u5Czb4lUJHYrbznup19EG4mVs9RNkj/cGybGadFIDPuoAlrQ16RQaZQ3O9RhcSxpqWqQXTt8Ge8EKQkrbB+rYFmUAJJzkfXqq3cwpvgEnCQuEPBpoqoqNKRE7C21QgUrGhAHcQ4cKserCUGTRWBHQpxCtjRpxJIt529vhRMvBVO0WUPP7PBrHUjjYy52pYSiSNl1+aWnZOqXiKDj9+c2PZ8MUUgygp+5KSBb8YZy0uXidOfjdGY9UvpVQxSck=

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "ht1VC1yf1zR3axK3DyrvOlg13aagve9PjJirxX0KhywS84aaPcAtMZqaxm3zx2aSx66boRFGnZh6plWM4Bxg2VnJfPWDFyhGi+bbyA5prOEklxfQDhDQ+nEFyDDN60ZAZDRBmhi8+9yNkPoxlIFtHOGeKr5shC86R2/p8Ohqs6bBCSrJW8hiYhcEzNkXrvB2KtZ1UfsMTzsp8h1ylNhYtKhIib0cpPomsH/NQQ4uOUE3iK4b7KvxvFMra9FFhsjC2P0kO6lz0ikdtEGU3xau8BgUhnIoFD43WZebYoUYe/Tr2e/r/9sqXGCFHX7X1u073TwH2U/S9u4EQWvipuTcHYgq6vBDi92q9v5MG4/marjZ6z8K7vz5ZjvgMmGwzPOxFlxAD1uJ68jCnxBrcvbboDyKYSXHrayrOJBIdYAqcxU/KljM8hKJI3c8vovl8y05lODM7aFuuNTgagKmHuq101TFXHJTtBdhMvPEp6yZoPxNsrnWIXbFgjnfUYY8nTH4EzWSRlcpQ8RBbB/Dvip5tjz+OaUcnR9LRh8YQF6GhpuaBO35yMlyFTNDWXRWPi10fR1tuPBcfufFEPO5E30KCPlymLUt28muKhV0U3dXGIBa8L6/jPf5on3whSG0uDNNXbkPFkyS+ow2Y6zseY80uwNRudjMlLsnHyIkFOtPV1U="

