openapi: 3.0.1
info:
  title: KMDP Endpoint Monitoring API
  description: |
    Reusable module that can be implemented for Java products using Spring to consolidate like code and surface the health endpoints (health, state, version) within any Java Spring implementation.
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Health
    description: |
      Return information about the application including schema version, status, system, version, environment, and components.
  - name: Version
    description: |
      Return the version of the application.
  - name: State
    description: |
      Return the state of the application including schema version, environment, and features.
paths:
  /health:
    get:
      tags:
        - Health
      summary: Display the health of the application.
      description: |
        Return information about the application including schema version, status, system, version, environment, and components.
      operationId: getHealthData
      responses:
        200:
          description: |
            A list of application information detailing the status of the system.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthData'
        500:
          description: |
            Unable to determine the health of the application.
          content: {}
        501:
          description: |
            This endpoint has not been implemented for this application.
          content: {}
  /version:
    get:
      tags:
        - Version
      summary: Display the version of the application.
      description: |
        Return the version of the application
      operationId: getVersionData
      responses:
        200:
          description: |
            The version of the application
          content:
            application/json:
              schema:
                type: string
        500:
          description: |
            Unable to determine the version of the application.
          content: {}
        501:
          description: |
            This endpoint has not been implemented for this application.
          content: {}
  /state:
    get:
      tags:
        - State
      summary: Display the state of the application.
      description: |
        Return information about the application state
      operationId: getStateData
      responses:
        200:
          description: |
            A list of application information detailing the state of the system.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateData'
        500:
          description: |
            Unable to determine the state of the application.
          content: {}
        501:
          description: |
            This endpoint has not been implemented for this application.
          content: {}
components:
  schemas:
    HealthData:
      description: The health endpoint schema
      allOf:
        - $ref: '#/components/schemas/DeployedApplication'
        - type: object
          properties:
            schemaInfo:
              $ref: '#/components/schemas/SchemaMetaInfo'
            at:
              type: string
    StateData:
      type: object
      properties:
        schemaInfo:
          $ref: '#/components/schemas/SchemaMetaInfo'
        serviceNowReference:
          $ref: '#/components/schemas/ServiceNowInfo'
        buildConfiguration:
          $ref: '#/components/schemas/BuildInfo'
        deploymentEnvironmentConfiguration:
          $ref: '#/components/schemas/MiscProperties'
        features:
          $ref: '#/components/schemas/Flags'
      description: The state endpoint schema
    CommonAppInfo:
      type: object
      properties:
        serviceNowReference:
          $ref: '#/components/schemas/ServiceNowInfo'
        name:
          type: string
        version:
          type: string
        status:
          $ref: '#/components/schemas/Status'
        statusMessage:
          type: string
        components:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationComponent'
      description: Attributes common to Software Applications, and Components thereof
    ApplicationComponent:
      allOf:
        - $ref: '#/components/schemas/CommonAppInfo'
        - type: object
          properties:
            details:
              $ref: '#/components/schemas/MiscProperties'
    DeployedApplication:
      allOf:
        - $ref: '#/components/schemas/CommonAppInfo'
        - type: object
          properties:
            deploymentEnvironment:
              $ref: '#/components/schemas/DeploymentEnvironment'
    Status:
      type: string
      description: The primary signal as to the health of the service or application.
      enum:
        - Up
        - Impaired
        - Down
    ServiceNowInfo:
      type: object
      properties:
        id:
          pattern: CI*
          type: string
          description: The ServiceNow configuration item ID
        url:
          type: string
          description: The ServiceNow configuration item URI
        display:
          type: string
          description: A human-readable display name for the system
    BuildInfo:
      type: object
      properties:
        artifactName:
          type: string
        groupId:
          type: string
        artifactId:
          type: string
        version:
          type: string
        buildTime:
          type: string
        details:
          $ref: '#/components/schemas/MiscProperties'
    DeploymentEnvironment:
      type: string
      description: The current application environment
      enum:
        - dev
        - test
        - int
        - uat
        - local
        - prod
        - unknown
    MiscProperties:
      type: object
      additionalProperties:
        type: string
    Flags:
      type: object
      additionalProperties:
        type: boolean
    SchemaMetaInfo:
      type: object
      properties:
        url:
          type: string
        version:
          type: string
